sudo: required
services:
  - docker

before_install:
  - docker build -t kaleido01/docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true kaleido01/docker-ci yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-ci"
  env: "DockerCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-145160279582"
  bucket_path: "docker-ci"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
